default:
  port: 3000
  database: 'mongodb://localhost/twars'
  apiServer: 'http://localhost:8080/api/'
  appServer: 'http://localhost:3000/'
  githubClientId: '3d1ce4b21c72eed40be3'
  githubClientSecret: 'fe406b1fdc3f386871979976e244e01224c933ac'
  callbackUrl: 'http://localhost:3000/login/github/callback'
  sessionTtl: 3600 # 60(MINUTE_PER_HOUR) * 60(SECONDS_PER_MINUTE)
test:
  port: 5000